[package]
name = "hello_cargo"
version = "0.1.0"
authors = ["Kamil Kiewisz <kamkie@outlook.com>"]
edition = "2018"

[dependencies]
log = "0.4.6"
simple_logger = "1.15.0"

iron = "0.6.0"

num = "0.4.0"

ansi_term = "0.12.1"
