[package]
name = "hello_cargo"
version = "0.1.0"
authors = ["Kamil Kiewisz <kamkie@outlook.com>"]
edition = "2018"

[dependencies]
log = "0.4.21"
simple_logger = "4.3.3"

iron = "0.6.0"

num = "0.4.2"

ansi_term = "0.12.1"
