[package]
name = "hello_cargo"
version = "0.1.0"
authors = ["Kamil Kiewisz <kamkie@outlook.com>"]

[dependencies]
log = "0.3.8"
simple_logger = "0.4.0"

iron = "0.5.1"
time = "0.1.38"

num = "0.1.39"

ansi_term = "0.9"
