[package]
name = "hello_cargo"
version = "0.1.0"
authors = ["Kamil Kiewisz <kamkie@outlook.com>"]

[dependencies]
log = "0.4.4"
simple_logger = "0.5.0"

iron = "0.6.0"
time = "0.1.40"

num = "0.2.0"

ansi_term = "0.11"
