[package]
name = "hello_cargo"
version = "0.1.0"
authors = ["Kamil Kiewisz <kamkie@outlook.com>"]
edition = "2018"

[dependencies]
log = "0.4.6"
simple_logger = "1.0.1"

iron = "0.6.0"
time = "0.1.42"

num = "0.2.0"

ansi_term = "0.11.0"
